### ISSUE TITLE
파일업로드용

### ISSUE THREAD

**Issue by hokyung-lee** [15zo/fe-group-sharing#6]
파일업로드용

**Comment by Sung0422** [comment]
![Promotion2](https://user-images.githubusercontent.com/95988685/175792212-337c2866-1d10-4049-9dd9-4f9ac6f84abf.svg)
![Promotion1](https://user-images.githubusercontent.com/95988685/175792214-02e3e1ca-8716-48d6-866b-f61af57a3332.svg)
![Promotion4](https://user-images.githubusercontent.com/95988685/175792216-688fa055-385f-4596-ba61-7a5dec9a663f.svg)
![Promotion3](https://user-images.githubusercontent.com/95988685/175792219-9442216d-c906-4e56-9c6a-7dbf2faca5ca.svg)
